language: perl

env:
  global:
    - PREREQS="ExtUtils::PkgConfig Module::Build File::Copy"
    - DOWNLOAD_LOC="http://rocky.github.io/libcdio-1.1.0rc1.tar.bz2"
    - DOWNLOAD_LOC="ftp://ftp.gnu.org/pub/gnu/libcdio/libcdio-${LIBCDIO_VERSION}.tar.gz"
  matrix:
    - LIBCDIO_VERSION="1.1.0"

install:
  # Prerequisites
  - sudo apt-get install swig
  - wget $DLOWNLOAD_LOC
  - tar -xpf libcdio-${LIBCDIO_VERSION}.tar.gz
  - cd libcdio-${LIBCDIO_VERSION} && ./configure --prefix=/usr && make && sudo make install && cd .. && rm -fr libcdio-${LIBCDIO_VERSION}
  - cpanm -v $PREREQS --notest .

script:
- make check

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

perl:
  - "5.26"
  - "5.24-shrplib"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
