language: perl

env:
  - PREREQS="ExtUtils::PkgConfig Module::Build File::Copy"

install:
  # Prerequisites
  - sudo apt-get install swig
  - wget ftp://ftp.gnu.org/pub/gnu/libcdio/libcdio-0.94.tar.gz
  - tar -xpf libcdio-0.94.tar.gz
  - cd libcdio-0.94 && ./configure --disable-shared --prefix=/usr && make && sudo make install && cd .. && rm -fr libcdio-0.94
  - cpanm $PREREQS

script:
- make check

after_failure:
  - cat /home/travis/.cpanm/work/*/build.log

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
